const Titles = [
    'Attack on Titan Trivia Quiz',
    'Death Note Kin Quiz',
    'Death Note Trivia Quiz',
    'Demon Slayer Breathing Style Quiz',
    'Demon Slayer Trivia Quiz',
    'Guess the Anime Character',
    'Guess the Attack on Titan Character',
    'Guess the Cowboy Bebop Character',
    'Guess the Death Note Character',
    'Guess the Demon Slayer Character',
    'Guess the Haikyuu Character',
    'Guess the Hunter x Hunter Character',
    'Guess the Kabaneri of the Iron Fortress Character',
    'Guess the My Hero Academia Character',
    'Guess the Naruto Character',
    'Guess the One Piece Character',
    'Guess the One Punch Man Character',
    'Guess the Sailor Moon Character',
    'Guess the Seven Deadly Sins Character',
    'Guess the Swort Art Online Character',
    'Guess the Tokyo Ghoul Character',
    'Guess the Tokyo Revengers Character',
    'Jujutsu Kaisen Quiz',
    'Kabaneri of the Iron Fortress Trivia Quiz',
    'My Hero Academia Trivia Quiz',
    'One Piece Trivia Quiz',
    'One Punch Man Trivia Quiz',
    'Tokyo Ghoul Trivia Quiz',
    'Tokyo Revengers Boyfriend Quiz',
    'Tokyo Revengers Kin Quiz',
    'Tokyo Revengers Trivia Quiz',
    'What is Your Demon Slayer Breathing Style?',
    'Which Demon Slayer Character Are You?',
    'Which Demon Slayer Demon Are You?',
    'Which Naruto Character Are You?',
    'Which One Punch Man Character Are You?',
]

export default Titles
